name: Stale Issues

on:
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: jvalkeal/stale@v3-patch1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 60
        days-before-close: 7
        stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove status/stale label or comment or this will be closed in 7 days'
        close-issue-message: 'Closing stale issue due to inactivity'
        stale-issue-label: status/stale
        close-issue-label: status/closed-as-stale
        exempt-issue-labels: status/on-hold
        operations-per-run: 5
        ascending: true
        debug-only: true
